# Generated by Django 5.0.1 on 2024-01-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tool", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="content",
            field=models.TextField(verbose_name="개발툴 설명"),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=24, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="tool",
            name="type",
            field=models.CharField(max_length=24, verbose_name="종류"),
        ),
    ]
