# Generated by Django 5.0.1 on 2024-01-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="제목")),
                (
                    "image",
                    models.ImageField(null=True, upload_to="", verbose_name="이미지"),
                ),
                ("content", models.TextField()),
                ("interest", models.IntegerField()),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                ("idea_inter", models.IntegerField(default=0, verbose_name="아이디어 관심도")),
            ],
        ),
    ]
