# Generated by Django 5.0.1 on 2024-01-17 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idea", "0002_remove_idea_idea_inter_alter_idea_interest"),
        ("tool", "0002_alter_tool_content_alter_tool_name_alter_tool_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="tool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tool.tool",
                verbose_name="예상 개발툴",
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="content",
            field=models.TextField(verbose_name="아이디어 설명"),
        ),
        migrations.AlterField(
            model_name="idea",
            name="image",
            field=models.ImageField(null=True, upload_to="", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="idea",
            name="title",
            field=models.CharField(max_length=30, verbose_name="아이디어명"),
        ),
    ]
