# Generated by Django 5.0.1 on 2024-01-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("year", models.CharField(max_length=32)),
                ("genre", models.CharField(max_length=32)),
                ("star", models.FloatField()),
                ("poster", models.ImageField(upload_to="images/")),
                ("time", models.IntegerField()),
                ("review", models.TextField()),
                ("director", models.CharField(max_length=32)),
                ("actor", models.CharField(max_length=32)),
            ],
        ),
    ]
