# Generated by Django 5.0.1 on 2024-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
